import { readFileSync, writeFileSync, renameSync } from "fs";
import { join, basename } from "path";
import { projectTraceDir } from "./store";
import { buildSession, loopTurns, turnSnippet, mainThread, continuationSummaryTurn } from "./session";
import { extractSessionId } from "./summarize";
import { readTracePairs, listTraceEntries, TAIL_BYTES, type TraceDirArg } from "./history";
import type { TracePair } from "./types";

// `cctrace title` — a human name for every session, generated by a model
// from the conversation's SPINE: the human's real prompts and the agent's
// final responses per working loop (loopTurns), main chat threads only —
// no tool calls, no tool results, no intermediate narration, no sub-agent
// threads. The digest is capped and front/back weighted (what the session
// was asked for + where it ended). Titles live per project store dir in
// titles.json keyed by session id (or "file:<name>" when the trace carries
// none) and surface in the dashboard, `history`, the view picker and the
// trace header. The runner is the user's own `claude -p` (their auth, their
// quota; --model picks the model, sonnet by default) — cctrace has no API
// key of its own and should not grow one for this.

export const TITLES_FILE = "titles.json";
/** Digest budget in characters — a few thousand tokens, whatever the model. */
export const DIGEST_CHARS = 12_000;
export const DEFAULT_TITLE_MODEL = "sonnet";

export interface TitleEntry {
  title: string;
  model: string;
  /** ISO time the title was generated. */
  at: string;
  /** Trace file the digest came from. */
  source: string;
}
export type Titles = Record<string, TitleEntry>;

export function readTitles(dir: string): Titles {
  try {
    const j = JSON.parse(readFileSync(join(dir, TITLES_FILE), "utf8"));
    return j && typeof j === "object" ? j : {};
  } catch {
    return {};
  }
}

/** Atomic rewrite (tmp + rename) — a reader mid-write never sees a torn file. */
export function writeTitles(dir: string, titles: Titles): void {
  const path = join(dir, TITLES_FILE);
  const tmp = `${path}.${process.pid}.tmp`;
  writeFileSync(tmp, JSON.stringify(titles, null, 1) + "\n");
  renameSync(tmp, path);
}

/** The key a session's title is stored under. */
export function titleKey(sessionId: string | undefined | null, traceBase: string): string {
  return sessionId ? sessionId : `file:${traceBase.replace(/\.jsonl(\.zst|\.gz)?$/, "")}`;
}

/** The stored title for a run/trace: by session id first, then by file. */
export function titleFor(dir: string, sessionId: string | undefined | null, traceBase?: string): string {
  const t = readTitles(dir);
  if (sessionId && t[sessionId]) return t[sessionId]!.title;
  if (traceBase) {
    const k = titleKey(null, traceBase);
    if (t[k]) return t[k]!.title;
  }
  return "";
}

/** One prompt/answer exchange of the spine. */
export interface DigestLoop {
  user: string;
  final: string;
}

/**
 * The spine of a session's main thread(s): per working loop, the human's
 * prompt and the agent's final text. Sub-agent threads (kind "agent") and
 * utilities (quota probe, the CLI's own title generation) are skipped;
 * tool_use/tool_result blocks never appear because only text blocks are
 * read (turnSnippet), and mid-loop assistant steps are not the final.
 */
export function sessionSpine(pairs: TracePair[], wire?: any): { sid: string; loops: DigestLoop[] }[] {
  const session = buildSession(pairs, wire);
  const out: { sid: string; loops: DigestLoop[] }[] = [];
  const chats = (session.threads || []).filter((t: any) => t.kind === "chat").sort((a: any, b: any) => (a.firstAt || 0) - (b.firstAt || 0));
  for (const t of chats) {
    const vis = (t.turns || []).filter((x: any) => !x.toolResultsOnly);
    const loops: DigestLoop[] = [];
    for (const loop of loopTurns(vis)) {
      // A loop headed by an automated notification or a continuation
      // summary has no human words — its final answer still counts.
      const headHuman = loop.head != null && !loop.headInjected && !continuationSummaryTurn(vis[loop.head].blocks);
      const user = headHuman ? turnSnippet(vis[loop.head].blocks) : "";
      const final = loop.final != null ? turnSnippet(vis[loop.final].blocks) : "";
      if (!user && !final) continue;
      loops.push({ user, final });
    }
    if (loops.length) out.push({ sid: t.sessionId || "", loops });
  }
  return out;
}

/**
 * Render loops to the model's input within `maxChars`: every loop when it
 * fits, else the first and last loops with a gap marker (what was asked
 * for + where it ended). Each side of a loop is clipped so one pasted
 * file cannot eat the budget.
 */
export function renderDigest(loops: DigestLoop[], maxChars = DIGEST_CHARS): string {
  const clip = (s: string, n: number) => (s.length > n ? s.slice(0, n) + " …" : s);
  const one = (l: DigestLoop, i: number) => {
    const parts = [];
    if (l.user) parts.push(`[${i + 1}] USER: ${clip(l.user.trim(), 700)}`);
    if (l.final) parts.push(`[${i + 1}] AGENT: ${clip(l.final.trim(), 500)}`);
    return parts.join("\n");
  };
  const all = loops.map(one);
  const total = all.reduce((n, s) => n + s.length + 2, 0);
  if (total <= maxChars) return all.join("\n\n");
  const head: string[] = [];
  const tail: string[] = [];
  let used = 40;
  let i = 0, j = all.length - 1;
  // Alternate front/back until the budget is spent — both ends matter.
  while (i <= j && used < maxChars) {
    if (used + all[i]!.length + 2 > maxChars) break;
    head.push(all[i]!); used += all[i]!.length + 2; i++;
    if (i > j) break;
    if (used + all[j]!.length + 2 > maxChars) break;
    tail.unshift(all[j]!); used += all[j]!.length + 2; j--;
  }
  const skipped = j - i + 1;
  return head.join("\n\n") + (skipped > 0 ? `\n\n[… ${skipped} exchange${skipped > 1 ? "s" : ""} omitted …]\n\n` : "\n\n") + tail.join("\n\n");
}

export function titlePrompt(digest: string, project?: string): string {
  return [
    "You name coding-agent sessions. Below is the spine of one session: the human's prompts and the agent's final answers, in order (tool calls omitted).",
    "Write ONE title for it: 4-9 words, specific to what was actually done or asked (name the component/bug/feature), no trailing period, no quotes, no leading verb like \"Session about\". Prefer the concrete outcome over the opening request when they differ.",
    project ? `Project: ${project}` : "",
    "Reply with the title only.",
    "",
    "<session>",
    digest,
    "</session>",
  ].filter((l) => l !== "").join("\n");
}

/** Post-process a model reply into a title: first line, unquoted, capped. */
export function cleanTitle(raw: string): string {
  let s = (raw || "").trim().split("\n").find((l) => l.trim()) || "";
  s = s.replace(/^["'“”`*#\s-]+|["'“”`*\s.]+$/g, "").trim();
  if (s.length > 100) s = s.slice(0, 97).trimEnd() + "…";
  return s;
}

export type TitleRunner = (prompt: string, model: string) => Promise<string>;

/** The default runner: the user's own `claude -p` (their auth). */
export const claudeRunner: TitleRunner = async (prompt, model) => {
  const proc = Bun.spawn(["claude", "-p", "--no-session-persistence", "--model", model, "--output-format", "text"], {
    stdin: new Blob([prompt]),
    stdout: "pipe",
    stderr: "pipe",
  });
  const timer = setTimeout(() => proc.kill(), 120_000);
  const [out, err] = await Promise.all([new Response(proc.stdout).text(), new Response(proc.stderr).text()]);
  const code = await proc.exited;
  clearTimeout(timer);
  if (code !== 0) throw new Error((err || out || `claude exited ${code}`).trim().split("\n")[0]);
  return out;
};

export interface TitleJob {
  key: string;
  sid: string;
  source: string;
  digest: string;
  loops: number;
}

/**
 * Plan: which sessions in `dirs` need a title. Reads each trace (tail
 * budget — the newest request re-sends the whole conversation, so the
 * spine survives), one job per session id (the file with the most loops
 * wins), skipping keys titles.json already has unless `force`.
 */
export async function planTitles(dirs: TraceDirArg, storeDir: string, wire: any, opts: { force?: boolean; onlyFile?: string } = {}): Promise<{ jobs: TitleJob[]; skipped: number }> {
  const have = readTitles(storeDir);
  const jobs = new Map<string, TitleJob>();
  let skipped = 0;
  const entries = listTraceEntries(dirs).filter((e) => !opts.onlyFile || e.path === opts.onlyFile || e.name === opts.onlyFile);
  for (const e of entries) {
    let pairs: TracePair[];
    try { pairs = (await readTracePairs(e.path, { tailBytes: TAIL_BYTES })).pairs; } catch { continue; }
    if (!pairs.length) continue;
    const spines = sessionSpine(pairs, wire);
    if (!spines.length) {
      // No chat thread at all (a bootstrap-only trace): nothing to name.
      continue;
    }
    for (const s of spines) {
      const key = titleKey(s.sid || firstSid(pairs, wire), e.name);
      if (!opts.force && have[key]) { skipped++; continue; }
      const prev = jobs.get(key);
      if (prev && prev.loops >= s.loops.length) continue;
      jobs.set(key, { key, sid: s.sid, source: e.name, digest: renderDigest(s.loops), loops: s.loops.length });
    }
  }
  return { jobs: [...jobs.values()], skipped };
}

function firstSid(pairs: TracePair[], wire: any): string {
  for (const p of pairs) { const s = extractSessionId(p, wire); if (s) return s; }
  return "";
}

/** Run the jobs with bounded concurrency; titles.json is rewritten after
 * every success so an interrupted run keeps what it earned. */
export async function applyTitles(
  storeDir: string,
  jobs: TitleJob[],
  opts: { model?: string; concurrency?: number; runner?: TitleRunner; project?: string; onDone?: (job: TitleJob, title: string | null, err?: string) => void },
): Promise<{ titled: number; failed: number }> {
  const model = opts.model || DEFAULT_TITLE_MODEL;
  const runner = opts.runner || claudeRunner;
  const n = Math.max(1, opts.concurrency || 4);
  let titled = 0, failed = 0, next = 0;
  const worker = async () => {
    while (next < jobs.length) {
      const job = jobs[next++]!;
      try {
        const title = cleanTitle(await runner(titlePrompt(job.digest, opts.project), model));
        if (!title) throw new Error("empty title");
        const titles = readTitles(storeDir); // re-read: other workers wrote
        titles[job.key] = { title, model, at: new Date().toISOString(), source: job.source };
        writeTitles(storeDir, titles);
        titled++;
        opts.onDone?.(job, title);
      } catch (err) {
        failed++;
        opts.onDone?.(job, null, err instanceof Error ? err.message : String(err));
      }
    }
  };
  await Promise.all(Array.from({ length: Math.min(n, jobs.length) }, worker));
  return { titled, failed };
}

/** A per-call cached lookup of titles for registry runs: the run's project
 * store dir's titles.json, by session id, then by trace file name. */
export function titleLookup(dataDir: string): (run: { projectPath?: string; sessionId?: string; logFile?: string }) => string {
  const cache = new Map<string, Titles>();
  return (run) => {
    if (!run.projectPath) return "";
    const dir = projectTraceDir(dataDir, run.projectPath);
    let t = cache.get(dir);
    if (!t) { t = readTitles(dir); cache.set(dir, t); }
    if (run.sessionId && t[run.sessionId]) return t[run.sessionId]!.title;
    if (run.logFile) { const k = titleKey(null, basename(run.logFile)); if (t[k]) return t[k]!.title; }
    return "";
  };
}

/** For callers holding pairs already (the view header): the main thread's
 * session id, to look its title up. */
export function mainSessionId(pairs: TracePair[], wire?: any): string {
  const t = mainThread(buildSession(pairs, wire).threads);
  return (t && t.sessionId) || firstSid(pairs, wire);
}
